services:
  - type: web
    name: syncaplus-live-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SYNCA_WS_SECRET
        value: change-this-secret
